# Generated by Django 6.0.3 on 2026-03-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='property_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('pg', 'Paying Guest (PG)'), ('hostel', 'Hostel'), ('resort', 'Resort'), ('apartment', 'Apartment')], default='hotel', max_length=20),
        ),
    ]
