services:

  postgres:
    image: postgres:16
    container_name: hms_postgres
    restart: always
    environment:
      POSTGRES_DB: hms
      POSTGRES_USER: hms
      POSTGRES_PASSWORD: hms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hms -d hms"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      target: ${BACKEND_BUILD_TARGET:-dev}
    container_name: hms_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/${BACKEND_ENV_FILE:-.env.local}
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres 

  frontend:
    build:
      context: ./frontend
      target: ${FRONTEND_BUILD_TARGET:-dev}
    container_name: hms_frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - ./frontend/${FRONTEND_ENV_FILE:-.env.local}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.27-alpine
    container_name: hms_nginx
    restart: always
    depends_on:
      - frontend
      - backend
    environment:
      - NGINX_ENVSUBST_FILTER=^NGINX_
      - NGINX_MAIN_DOMAIN=${NGINX_MAIN_DOMAIN}
      - NGINX_BACKEND_DOMAIN=${NGINX_BACKEND_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/${NGINX_CONF_FILE:-default.local.conf}:/etc/nginx/templates/default.conf.template:ro
      - ./ssl:/etc/nginx/ssl:ro

volumes:
  postgres_data: