services:
  backend:
    build:
      context: ./backend
      target: prod
    env_file:
      - ./backend/${BACKEND_ENV_FILE:-.env.prod}
    volumes:
      - static_data:/app/staticfiles

  frontend:
    build:
      context: ./frontend
      target: prod
    env_file:
      - ./frontend/${FRONTEND_ENV_FILE:-.env.prod}
    volumes: []
    environment:
      - NODE_ENV=production
    command: sh -c "npm run build && npm run start -- -H 0.0.0.0 -p 3000"

  nginx:
    environment:
      - NGINX_ENVSUBST_FILTER=^NGINX_
      - NGINX_MAIN_DOMAIN=${NGINX_MAIN_DOMAIN:-hms.rest}
      - NGINX_BACKEND_DOMAIN=${NGINX_BACKEND_DOMAIN:-backend.hms.rest}
    volumes:
      - ./nginx/${NGINX_CONF_FILE:-default.prod.ssl.conf}:/etc/nginx/templates/default.conf.template:ro
      - ./ssl:/etc/nginx/ssl:ro
      - static_data:/var/www/backend_static:ro
      - ./backend/media:/var/www/media:ro

volumes:
  static_data:

