services:

  postgres:
    image: postgres:16
    container_name: hms_postgres
    restart: always
    environment:
      POSTGRES_DB: hms
      POSTGRES_USER: hms
      POSTGRES_PASSWORD: hms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: hms_backend
    env_file:
      - ./backend/${BACKEND_ENV_FILE:-.env.local}
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres 

  frontend:
    build: ./frontend
    container_name: hms_frontend
    env_file:
      - ./frontend/${FRONTEND_ENV_FILE:-.env.local}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.27-alpine
    container_name: hms_nginx
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/${NGINX_CONF_FILE:-default.local.conf}:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data: