# Generated by Django 6.0.3 on 2026-03-20 05:59

import apps.attachments.models.attachment
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hms_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.BigIntegerField(db_index=True)),
                ('file_path', models.TextField(blank=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('uploaded_by', models.BigIntegerField(blank=True, null=True)),
                ('storage_folder', models.CharField(blank=True, editable=False, max_length=64)),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('saved_filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('file', models.FileField(upload_to=apps.attachments.models.attachment.attachment_upload_to)),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
